### ISSUE TITLE
Provide a link to Chrome Web Store support page

### ISSUE THREAD

**Issue by shanebell** [shanebell/JaSON#32]
Provide a way for users to provide feedback.

Does the Chrome web store provide a way to do this?
Maybe use Uservoice or similar?

**Comment by rottina** [comment]
There is a  "Reviews" and "Support" tab for the app in the Chrome Store.

**Comment by shanebell** [comment]
Add this link to the about modal:

https://chrome.google.com/webstore/detail/jason/oealdlhfjifhgbmjnenhkgffglaibojf/support
