### ISSUE TITLE
Chrome Web Store Link Broken. 

### ISSUE THREAD

**Issue by cr305MSFT** [shanebell/JaSON#87]
The link to you Chrome Extension is Broken.

https://chrome.google.com/webstore/detail/jason/oealdlhfjifhgbmjnenhkgffglaibojf

**Comment by shanebell** [comment]
JaSON was temporarily pulled from the Chrome Web Store for approx 2 weeks because it did not include a privacy policy which was recently made a requirement by Google. This has been fixed and the link is active again now.
